name: Setup Rust
description: Setup Rust toolchain and cache

inputs:
  components:
    description: Rust components to install (e.g. rustfmt, clippy)
    required: false
    default: ''
  targets:
    description: Rust targets to install (e.g. wasm32-unknown-unknown)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}
    - uses: Swatinem/rust-cache@v2
